name: Request Export

on:
  schedule:
    - cron: "6 16 * * 3" # at 04:06am on Wednesday NZST
  workflow_dispatch:

jobs:
  request-export:
    runs-on: ubuntu-latest

    steps:
      - name: ‚è¨ Checkout code
        uses: actions/checkout@v3

      - name: üî¢ Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 25.x

      - name: ‚è¨ Install
        run: |
          yarn

      - name: 0. Request to generate an export from the source dataset
        run: npm start "*" requestExport
        env:
          REACT_APP_LDS_KEY: ${{ secrets.REACT_APP_LDS_KEY }}
